[package]
name = "jrnl"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.6", features = ["derive"] }
kamadak-exif = "0.5.4"
walkdir = "2"
anyhow = "1.0.52"